In [13]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.ensemble import RandomForestRegressor

In [2]:
df = pd.read_csv('results_DO_NOT_DELETE.csv',error_bad_lines=False)

b'Skipping line 690: expected 14 fields, saw 15\nSkipping line 2482: expected 14 fields, saw 15\nSkipping line 2499: expected 14 fields, saw 15\n'

In [3]:
df = df.reset_index()

In [4]:
df.rename(columns= {'index': 'Title',
                   'Title': 'Condition',
                    'Condition': 'Material',
                    "Material": "Frame Size",
                    'Frame Size':'Wheel Size',
                    'Wheel Size': 'Front Travel',
                    'Front Travel': 'Rear Travel',
                    'Rear Travel':'Price',
                    'Price' : 'City',
                    'City' : 'State/Prov',
                    'State/Prov':'Country',
                    'Country':'Description',
                    'Description': 'Date'
                    
                   },inplace=True)

In [5]:
df.drop('Date Posted',inplace=True,axis = 1)

In [6]:
df.groupby('Wheel Size').count()

,Title,Condition,Material,Frame Size,Front Travel,Rear Travel,Price,City,State/Prov,Country,Description,Date
Wheel Size,,,,,,,,,,,,
0 mm Rigid,3,3,3,3,3,3,3,3,3,3,3,3
130 mm,3,3,3,3,3,3,3,3,3,3,3,3
140 mm,2,2,2,2,2,2,2,2,2,2,2,2
150 mm,3,3,3,3,3,3,3,3,3,3,3,3
16 or less,1,1,1,1,1,1,1,1,1,1,1,1
160 mm,5,5,5,5,5,5,5,5,5,5,5,5
170 mm,5,5,5,5,5,5,5,5,5,5,5,5
20,1,1,1,1,1,1,1,1,1,1,1,1
24,7,7,7,7,7,7,7,7,7,7,7,7
26,273,273,273,273,273,273,273,273,273,273,273,273
275 650B,1879,1879,1879,1879,1879,1879,1879,1878,1879,1879,1879,1876
29,1474,1474,1474,1474,1474,1474,1474,1474,1474,1474,1474,1474
40 mm,1,1,1,1,1,1,1,1,1,1,1,1
650C,1,1,1,1,1,1,1,1,1,1,1,1
700C,10,10,10,10,10,10,10,10,10,10,10,10
80 mm,1,1,1,1,1,1,1,1,1,1,1,1

In [7]:
def Check_Material(string):
    if string == 'Aluminium' or string == 'Carbon Fiber' or string == 'Chromoly' or string== 'Steel' or string =='Titanium':
        return True
    else:
        return False
def Check_Wheel(string):
    if '275' in string or string == '29' or string == '26':
        return True
    else:
        return False

def convert_string_int(input_string):
    nums = '1234567890'
    string = ''
    for char in input_string:
        if char in nums:
            string+= char
    return int(string)
def convert_to_us(input_string):
    if 'CAD' in input_string:
        return int(convert_string_int(input_string)*.71)
    else:
        return convert_string_int(input_string)

In [8]:
df = df[df['Material'].apply(lambda x : Check_Material(x))]
df = df[df['Wheel Size'].apply(lambda z: Check_Wheel(z))]
df = df[df['Front Travel'] != '0 mm Hardtail' ]
df['Front Travel'] = df['Front Travel'].apply(lambda x : convert_string_int(x))
df['Rear Travel'] = df['Rear Travel'].apply(lambda x : convert_string_int(x))

In [9]:
def remove_resonable_trades(input_string):
    if 'CAD' in input_string or 'USD' in input_string:
        return True
    else:
        return False

In [10]:
df = df[df['Price'].apply(lambda x : remove_resonable_trades(x))]

In [11]:
df['Price'] = df['Price'].apply(lambda x : convert_to_us(x))

In [19]:
df.groupby('Wheel Size').count()

,Title,Condition,Material,Frame Size,Front Travel,Rear Travel,Price,City,State/Prov,Country,Description,Date
Wheel Size,,,,,,,,,,,,
26,262,262,262,262,262,262,262,262,262,262,262,262
275 650B,1849,1849,1849,1849,1849,1849,1849,1848,1849,1849,1849,1846
29,1455,1455,1455,1455,1455,1455,1455,1455,1455,1455,1455,1455

In [22]:
final_data = pd.get_dummies(df,columns=Condition,Material,Frame Size,drop_first=True)

SyntaxError: invalid syntax (<ipython-input-22-e2902cd4665e>, line 1)

In [15]:
X = df[['Condition','Material', 'Frame Size','Front Travel', 'Rear Travel']]
y = df['Price']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [17]:
randforest = RandomForestRegressor( n_estimators=100)

ValueError: could not convert string to float: 'Excellent'

In [ ]:
randforest.fit(X_test,y_test)